import { BunnyPurple, Next, NextBlue, Vector } from '@/components/icons';
import { secredCodeGift, chest, connectWallet, medalSilver, news, univ, telegram, twitter, youtube, retweet, mimeFi, instagram } from '@/components/images';

export const Title = 'EarnTitle';

export const Onboarding = [
  {
    id: 0,
    image: connectWallet,
    size: 'w-[22px] h-[16px]',
    text: 'OnboardingWallet',
    icon: <BunnyPurple width={25} height={25}/>,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 1,
    image: medalSilver,
    size: 'w-[20px] h-[25px]',
    text: 'UpToSilver',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '10K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 2,
    image: news,
    size: 'w-[20px] h-[20px]',
    text: 'OnboardingJoinCom',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '1M',
    iconCheck: <Vector width={26} height={21}/>,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 3,
    image: univ,
    size: 'w-[20px] h-[20px]',
    text: 'OnboardingRtPost',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '150K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 4,   
    image: univ,
    size: 'w-[20px] h-[20px]', 
    text: 'OnboardingCoin',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 5,
    image: univ,
    size: 'w-[20px] h-[20px]',
    text: 'OnboardingAnnouncement',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
];

export const Explore = [
  {
    id: 0,
    image: telegram,
    size: 'w-[22px] h-[21.79px]',
    text: 'ExploreJoin',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 1,
    image: twitter,
    size: 'w-[20px] h-[19px]',
    text: 'ExploreFollowX',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '10K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 2,
    image: news,
    size: 'w-[20px] h-[20px]',
    text: 'ExploreNerdBunnyCom',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '1M',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 3,
    image: youtube,
    size: 'w-[23px] h-[23px]',
    text: 'ExploreFollowYouTube',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '150K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 4,
    image: retweet,
    size: 'w-[23px] h-[23px]',
    text: 'ExploreRtPost ',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '150K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 5,
    image: telegram,
    size: 'w-[22px] h-[21.79px]',
    text: 'ExploreMemeFi',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 6,
    image: twitter,
    size: 'w-[20px] h-[19px]',
    text: 'ExploreTiktok',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 6,
    image: mimeFi,
    size: 'w-[26px] h-[27px]',
    text: 'ExploreMemeFiCoin',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
  {
    id: 7,
    image: instagram,
    size: 'w-[27px] h-[27px]',
    text: 'ExploreFollowInstagram',
    icon: <BunnyPurple width={25} height={25} />,
    reward: '5K',
    iconCheck: <Vector width={26} height={21} />,
    iconRight: <Next width={20} height={20} />,
  },
];

export const Actions = [
  {
    id: 0,
    title: 'Invite',
    iconLeft: secredCodeGift,
    size:'w-[23px] h-[24px]',
    bgColor: 'bg-YellowSecond shadow-YellowSecond',
    text: 'InviteDescription',
    iconRight: <NextBlue width={8} height={12.63} />,
    link: '/friend',
  },
  {
    id: 1,
    title: 'DailyCryptoLearningTask',
    iconLeft: chest,
    size: 'w-[27px] h-[20px]',
    bgColor: 'bg-BlueThird shadow-BlueThird',
    text: 'DailyCryptoLearningTaskDescription',
    iconRight: <NextBlue width={8} height={12.63} />,
    link: '/dailytask',
  }
];